name: 'vev/deploy-widget-package'
description: 'Deploys a Vev Widget Package in your repository'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  token:
    description: 'API key'
    required: true
  dev-deploy:
    description: '(non-public) Deploy to Vev staging environment'
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.dev-deploy }}
